with open('index.html', 'r', encoding='utf-8') as f:
    idx_content = f.read()

with open('temp_extract/code.html', 'r', encoding='utf-8') as f:
    code_content = f.read()

split_str = '<!-- GenAI Summary Section -->'

idx_top = idx_content.split(split_str)[0]
code_bottom = split_str + code_content.split(split_str)[1]

code_bottom = code_bottom.split('<!-- html2pdf.js for Client-Side PDF Generation -->')[0]
code_bottom = code_bottom.split('</body>')[0]

pdf_template = """
    <!-- Hidden PDF Report Template -->
    <div id="pdf-report-template" class="hidden">
        <div class="pdf-container">
            <div class="pdf-header">
                <h1>Sentiment Analytics Report</h1>
                <p>Fine Aggregate Score Distribution & 7-Day Trends</p>
                <div class="pdf-timestamp" id="pdf-timestamp"></div>
            </div>
            
            <div class="pdf-row">
                <div class="pdf-col pdf-chart-col">
                    <h2>Fine Aggregate Score Distribution</h2>
                    <div id="pdf-percentages" class="pdf-stats"></div>
                    <img id="pdf-doughnut-img" src="" alt="Score Distribution">
                </div>
                <div class="pdf-col pdf-trend-col">
                    <h2>7-Day Sentiment Trends</h2>
                    <img id="pdf-trend-img" src="" alt="7-Day Trends">
                </div>
            </div>

            <div class="pdf-signals-section">
                <h2>Live Signals Breakdown</h2>
                <div class="pdf-signals-grid">
                    <div class="pdf-signal-col">
                        <h3 class="pos-text">Positive</h3>
                        <div id="pdf-pos-samples"></div>
                    </div>
                    <div class="pdf-signal-col">
                        <h3 class="neu-text">Neutral</h3>
                        <div id="pdf-neu-samples"></div>
                    </div>
                    <div class="pdf-signal-col">
                        <h3 class="neg-text">Negative</h3>
                        <div id="pdf-neg-samples"></div>
                    </div>
                </div>
            </div>
            
            <div class="pdf-summary-section">
                <h2>AI Executive Summary</h2>
                <p id="pdf-ai-summary"></p>
            </div>
            
            <div class="pdf-footer">
                <p>CONFIDENTIAL AND PROPRIETARY. GENERATED BY SENTIMENT ANALYTICS.</p>
            </div>
        </div>
    </div>

    <!-- html2pdf.js for Client-Side PDF Generation -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js"></script>
    <script src="script.js"></script>
</body>
</html>
"""

new_idx = idx_top + code_bottom + pdf_template
with open('index.html', 'w', encoding='utf-8') as f:
    f.write(new_idx)

print('Restored index.html')
